### ISSUE TITLE
Support for multiselect filters

### ISSUE THREAD

**Issue by danslo** [hyva-themes/magento2-hyva-admin#48]
Should be an easy one to do. Will potentially work on this issue myself.

**Comment by Vinai** [comment]
That would be super duper cool 😎

**Comment by Jacques03** [comment]
Hi,

This would be a nice feature to avoid having to install complex layered navigation module.

Is it planned ?

Thanks !

**Comment by Vinai** [comment]
@Jacques03 I think you are confusing this module with the store front layered navigation.

**Comment by Jacques03** [comment]
@Vinai oups yes, sorry.
Would be nice though :)
