### ISSUE TITLE
I want to show " I'm not Robot." on forgot password page.

### ISSUE THREAD

**Issue by MahamMubashir** [hyva-themes/magento2-hyva-admin#60]
I want to show " I'm not Robot." on forgot password page. But this Recaptcha always appears. Please can anyone help me with
![screenshot-odoo eguanacommerce com-2021 07 08-12_43_05](https://user-images.githubusercontent.com/38991060/124882684-143fd100-dfea-11eb-9dc0-9f43975fd786.png)
 this?

**Comment by Vinai** [comment]
I think you got the wrong repo. Hyvä-Admin has nothing to do with the forgot password page or authentication or captchas.

**Comment by MahamMubashir** [comment]
@Vinai Can you please guide me on where should I can ask about this issue?
I am getting this issue... in hyva theme... I am not a robot Recaptcha is not showing properly.

Thank You

**Comment by Vinai** [comment]
If this is a Hyva question, ask in Slack.
