### ISSUE TITLE
Configurable Product Image Gallery Sort Order

### ISSUE THREAD

**Issue by MahamMubashir** [hyva-themes/magento2-hyva-admin#61]
Issue: When we set the sort order from the admin panel then that sort order does not affect at frontend

Analysis and Finding:

1: This issue does not exist in the Luma theme

2: In the Hyva theme this issue exists only for configurable products

So this is the issue of Hyva theme

**Comment by Vinai** [comment]
Thanks for reaching out, but this is the wrong repository. please check the list of issues and open a new one if there is none already in the appropriate repository on the Hyvä gitlab.
