### ISSUE TITLE
Menu on mobile > can't scroll down to see more subcategories

### ISSUE THREAD

**Issue by Jacques03** [hyva-themes/magento2-hyva-admin#65]
Hi,

On mobile, if you have a lot of subcategories (I have 14) in a main category, you can't scroll down to see the remaining subcategories:

Ex here, on Iphone 11Pro:

<img width="277" alt="Capture d’écran 2022-02-05 à 13 41 42" src="https://user-images.githubusercontent.com/9104241/152642572-d00f1fae-f8d2-4a01-93b3-e8fc02867c22.png">

I'm not able to see the remaining subcategories scrolling dow.

Thanks.

Jacques

**Comment by Jacques03** [comment]
Sorry, this is of course not about Hyva admin, but Hyva theme

**Comment by Vinai** [comment]
Hi @Jacques03 , here is a link to the related issue in our private Gitlab: https://gitlab.hyva.io/hyva-themes/magento2-default-theme/-/issues/301
