### ISSUE TITLE
404 link in repo description

### ISSUE THREAD

**Issue by tmotyl** [hyva-themes/magento2-hyva-admin#72]
is: [hyva.io/hyva-admin.html](https://hyva.io/hyva-admin.html)
probably shoul be:
https://docs.hyva.io/hyva-admin/index.html

**Comment by Vinai** [comment]
Good catch!
I think it would be better to link to https://hyva-themes.github.io/magento2-hyva-admin/ directly

**Comment by Vinai** [comment]
Thanks again :)
