### ISSUE TITLE
DOMDocument::loadXML() expects parameter 1 to be string, object given

### ISSUE THREAD

**Issue by VincentMarmiesse** [hyva-themes/magento2-hyva-admin#8]
Hi,

It seems there is an issue in [the `mergeFile` function](https://github.com/hyva-themes/magento2-hyva-admin/blob/main/Model/Config/GridConfigReader.php#L78) of the `GridConfigReader` class.

The `merge` function of `XmlDom $merged` [requires a `string`](https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/Config/Dom.php#L146) and but you're calling it with a `XmlDom` as parameter.

Am I missing something here? It should be `$merged->merge($content);` or something like that imo.

Currently, I have the following error in my logs:
```
main.CRITICAL: Warning: DOMDocument::loadXML() expects parameter 1 to be string, object given in /var/www/html/vendor/magento/framework/Config/Dom.php on line 456 [] []
```

Thank you for your work!

**Comment by Vinai** [comment]
Thanks for your report!
What Magento and PHP versions are you using?

**Comment by VincentMarmiesse** [comment]
Hi, 
I am using Magento 2.4.1 and PHP 7.4.11.

**Comment by Vinai** [comment]
Just pushed release 1.0.3 that fixes the issue. Thanks again!
